name: Vite Vue2 打包构建

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: 安装依赖
        run: npm install

      - name: 打包项目
        run: npm run build

      - name: 上传 dist 打包产物
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
